name: pre-commit

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.17.1
      - uses: pre-commit/action@v3.0.0
      - name: add pnpm & setup pnpm
        run: npm i -g pnpm && pnpm setup
      - name: code format
        run: pnpm css-fix
